# 1. Conexão com o Banco de Dados (MySQL no Docker)
# O "db" no link abaixo é o nome do serviço que demos no docker-compose!
spring.datasource.url=jdbc:mysql://db:3306/fusion_analytics
spring.datasource.username=root
spring.datasource.password=senha_segura

# 2. Configurações do Hibernate (O "Tradutor" de Java para SQL)
# O 'update' faz o Java criar as tabelas faltantes sozinho
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Porta da Aplicação
server.port=8080